// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mutter.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// output_type indicates whether this is stdout or stderr.
type ExecuteStreamResponse_OutputType int32

const (
	ExecuteStreamResponse_STDOUT ExecuteStreamResponse_OutputType = 0
	ExecuteStreamResponse_STDERR ExecuteStreamResponse_OutputType = 1
)

// Enum value maps for ExecuteStreamResponse_OutputType.
var (
	ExecuteStreamResponse_OutputType_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	ExecuteStreamResponse_OutputType_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x ExecuteStreamResponse_OutputType) Enum() *ExecuteStreamResponse_OutputType {
	p := new(ExecuteStreamResponse_OutputType)
	*p = x
	return p
}

func (x ExecuteStreamResponse_OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteStreamResponse_OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_mutter_proto_enumTypes[0].Descriptor()
}

func (ExecuteStreamResponse_OutputType) Type() protoreflect.EnumType {
	return &file_mutter_proto_enumTypes[0]
}

func (x ExecuteStreamResponse_OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteStreamResponse_OutputType.Descriptor instead.
func (ExecuteStreamResponse_OutputType) EnumDescriptor() ([]byte, []int) {
	return file_mutter_proto_rawDescGZIP(), []int{7, 0}
}

// IndexRequest triggers re-indexing of scripts in the workspace.
type IndexRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// force forces a full re-index even if the index is up-to-date.
	Force         bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_mutter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mutter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_mutter_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// IndexResponse returns the result of the indexing operation.
type IndexResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scripts_found is the number of hashfm-annotated scripts discovered.
	ScriptsFound int32 `protobuf:"varint,1,opt,name=scripts_found,json=scriptsFound,proto3" json:"scripts_found,omitempty"`
	// errors is a list of any errors encountered during indexing.
	Errors        []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_mutter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mutter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_mutter_proto_rawDescGZIP(), []int{1}
}

func (x *IndexResponse) GetScriptsFound() int32 {
	if x != nil {
		return x.ScriptsFound
	}
	return 0
}

func (x *IndexResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// RouteRequest matches a natural language query to scripts.
type RouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query is the natural language input from the user.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// confidence_threshold overrides the configured threshold for this request.
	ConfidenceThreshold float32 `protobuf:"fixed32,2,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_mutter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mutter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_mutter_proto_rawDescGZIP(), []int{2}
}

func (x *RouteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RouteRequest) GetConfidenceThreshold() float32 {
	if x != nil {
		return x.ConfidenceThreshold
	}
	return 0
}

// RouteResponse returns the best matching script(s) for the query.
type RouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// matches is the list of matched scripts, sorted by confidence.
	Matches []*RouteMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	// query_normalized is the normalized form of the query (with chain syntax).
	QueryNormalized string `protobuf:"bytes,2,opt,name=query_normalized,json=queryNormalized,proto3" json:"query_normalized,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_mutter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mutter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_mutter_proto_rawDescGZIP(), []int{3}
}

func (x *RouteResponse) GetMatches() []*RouteMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *RouteResponse) GetQueryNormalized() string {
	if x != nil {
		return x.QueryNormalized
	}
	return ""
}

// RouteMatch represents a single routing match.
type RouteMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// script_path is the absolute path to the matched script.
	ScriptPath string `protobuf:"bytes,1,opt,name=script_path,json=scriptPath,proto3" json:"script_path,omitempty"`
	// script_name is the name of the matched script.
	ScriptName string `protobuf:"bytes,2,opt,name=script_name,json=scriptName,proto3" json:"script_name,omitempty"`
	// description is the script's description from the hashfm block.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// confidence is the similarity score (0.0 to 1.0).
	Confidence float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// usage shows how to invoke the script with arguments.
	Usage         string `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMatch) Reset() {
	*x = RouteMatch{}
	mi := &file_mutter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMatch) ProtoMessage() {}

func (x *RouteMatch) ProtoReflect() protoreflect.Message {
	mi := &file_mutter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMatch.ProtoReflect.Descriptor instead.
func (*RouteMatch) Descriptor() ([]byte, []int) {
	return file_mutter_proto_rawDescGZIP(), []int{4}
}

func (x *RouteMatch) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *RouteMatch) GetScriptName() string {
	if x != nil {
		return x.ScriptName
	}
	return ""
}

func (x *RouteMatch) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RouteMatch) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RouteMatch) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

// ExecuteRequest requests execution of a script.
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// script_path is the path to the script to execute.
	ScriptPath string `protobuf:"bytes,1,opt,name=script_path,json=scriptPath,proto3" json:"script_path,omitempty"`
	// arguments maps argument names to values for template rendering.
	Arguments map[string]string `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// execution_id is an optional ID for tracking the execution in the session buffer.
	ExecutionId   string `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_mutter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mutter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_mutter_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ExecuteRequest) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ExecuteRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// ExecuteResponse returns the result of script execution.
type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// execution_id is the ID of this execution in the session buffer.
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// exit_code is the exit code of the script.
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// stdout is the captured standard output.
	Stdout string `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// stderr is the captured standard error.
	Stderr string `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// error is any execution error (not the same as non-zero exit code).
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_mutter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mutter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_mutter_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ExecuteStreamResponse streams execution output in real-time.
type ExecuteStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// execution_id is the ID of this execution.
	ExecutionId string                           `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	OutputType  ExecuteStreamResponse_OutputType `protobuf:"varint,2,opt,name=output_type,json=outputType,proto3,enum=mutter.v1.ExecuteStreamResponse_OutputType" json:"output_type,omitempty"`
	// data is the output data chunk.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// is_complete indicates this is the final message for this execution.
	IsComplete bool `protobuf:"varint,4,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	// exit_code is only set in the final message.
	ExitCode      int32 `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStreamResponse) Reset() {
	*x = ExecuteStreamResponse{}
	mi := &file_mutter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStreamResponse) ProtoMessage() {}

func (x *ExecuteStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mutter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStreamResponse.ProtoReflect.Descriptor instead.
func (*ExecuteStreamResponse) Descriptor() ([]byte, []int) {
	return file_mutter_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteStreamResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteStreamResponse) GetOutputType() ExecuteStreamResponse_OutputType {
	if x != nil {
		return x.OutputType
	}
	return ExecuteStreamResponse_STDOUT
}

func (x *ExecuteStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecuteStreamResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *ExecuteStreamResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_mutter_proto protoreflect.FileDescriptor

const file_mutter_proto_rawDesc = "" +
	"\n" +
	"\fmutter.proto\x12\tmutter.v1\"$\n" +
	"\fIndexRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"L\n" +
	"\rIndexResponse\x12#\n" +
	"\rscripts_found\x18\x01 \x01(\x05R\fscriptsFound\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"W\n" +
	"\fRouteRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x121\n" +
	"\x14confidence_threshold\x18\x02 \x01(\x02R\x13confidenceThreshold\"k\n" +
	"\rRouteResponse\x12/\n" +
	"\amatches\x18\x01 \x03(\v2\x15.mutter.v1.RouteMatchR\amatches\x12)\n" +
	"\x10query_normalized\x18\x02 \x01(\tR\x0fqueryNormalized\"\xa6\x01\n" +
	"\n" +
	"RouteMatch\x12\x1f\n" +
	"\vscript_path\x18\x01 \x01(\tR\n" +
	"scriptPath\x12\x1f\n" +
	"\vscript_name\x18\x02 \x01(\tR\n" +
	"scriptName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12\x14\n" +
	"\x05usage\x18\x05 \x01(\tR\x05usage\"\xda\x01\n" +
	"\x0eExecuteRequest\x12\x1f\n" +
	"\vscript_path\x18\x01 \x01(\tR\n" +
	"scriptPath\x12F\n" +
	"\targuments\x18\x02 \x03(\v2(.mutter.v1.ExecuteRequest.ArgumentsEntryR\targuments\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\x0fExecuteResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x80\x02\n" +
	"\x15ExecuteStreamResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12L\n" +
	"\voutput_type\x18\x02 \x01(\x0e2+.mutter.v1.ExecuteStreamResponse.OutputTypeR\n" +
	"outputType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1f\n" +
	"\vis_complete\x18\x04 \x01(\bR\n" +
	"isComplete\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\"$\n" +
	"\n" +
	"OutputType\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x012\x99\x02\n" +
	"\rMutterService\x12:\n" +
	"\x05Index\x12\x17.mutter.v1.IndexRequest\x1a\x18.mutter.v1.IndexResponse\x12:\n" +
	"\x05Route\x12\x17.mutter.v1.RouteRequest\x1a\x18.mutter.v1.RouteResponse\x12@\n" +
	"\aExecute\x12\x19.mutter.v1.ExecuteRequest\x1a\x1a.mutter.v1.ExecuteResponse\x12N\n" +
	"\rExecuteStream\x12\x19.mutter.v1.ExecuteRequest\x1a .mutter.v1.ExecuteStreamResponse0\x01B,Z*github.com/sidisinsane/mutter/api/proto/v1b\x06proto3"

var (
	file_mutter_proto_rawDescOnce sync.Once
	file_mutter_proto_rawDescData []byte
)

func file_mutter_proto_rawDescGZIP() []byte {
	file_mutter_proto_rawDescOnce.Do(func() {
		file_mutter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mutter_proto_rawDesc), len(file_mutter_proto_rawDesc)))
	})
	return file_mutter_proto_rawDescData
}

var file_mutter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mutter_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mutter_proto_goTypes = []any{
	(ExecuteStreamResponse_OutputType)(0), // 0: mutter.v1.ExecuteStreamResponse.OutputType
	(*IndexRequest)(nil),                  // 1: mutter.v1.IndexRequest
	(*IndexResponse)(nil),                 // 2: mutter.v1.IndexResponse
	(*RouteRequest)(nil),                  // 3: mutter.v1.RouteRequest
	(*RouteResponse)(nil),                 // 4: mutter.v1.RouteResponse
	(*RouteMatch)(nil),                    // 5: mutter.v1.RouteMatch
	(*ExecuteRequest)(nil),                // 6: mutter.v1.ExecuteRequest
	(*ExecuteResponse)(nil),               // 7: mutter.v1.ExecuteResponse
	(*ExecuteStreamResponse)(nil),         // 8: mutter.v1.ExecuteStreamResponse
	nil,                                   // 9: mutter.v1.ExecuteRequest.ArgumentsEntry
}
var file_mutter_proto_depIdxs = []int32{
	5, // 0: mutter.v1.RouteResponse.matches:type_name -> mutter.v1.RouteMatch
	9, // 1: mutter.v1.ExecuteRequest.arguments:type_name -> mutter.v1.ExecuteRequest.ArgumentsEntry
	0, // 2: mutter.v1.ExecuteStreamResponse.output_type:type_name -> mutter.v1.ExecuteStreamResponse.OutputType
	1, // 3: mutter.v1.MutterService.Index:input_type -> mutter.v1.IndexRequest
	3, // 4: mutter.v1.MutterService.Route:input_type -> mutter.v1.RouteRequest
	6, // 5: mutter.v1.MutterService.Execute:input_type -> mutter.v1.ExecuteRequest
	6, // 6: mutter.v1.MutterService.ExecuteStream:input_type -> mutter.v1.ExecuteRequest
	2, // 7: mutter.v1.MutterService.Index:output_type -> mutter.v1.IndexResponse
	4, // 8: mutter.v1.MutterService.Route:output_type -> mutter.v1.RouteResponse
	7, // 9: mutter.v1.MutterService.Execute:output_type -> mutter.v1.ExecuteResponse
	8, // 10: mutter.v1.MutterService.ExecuteStream:output_type -> mutter.v1.ExecuteStreamResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mutter_proto_init() }
func file_mutter_proto_init() {
	if File_mutter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mutter_proto_rawDesc), len(file_mutter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mutter_proto_goTypes,
		DependencyIndexes: file_mutter_proto_depIdxs,
		EnumInfos:         file_mutter_proto_enumTypes,
		MessageInfos:      file_mutter_proto_msgTypes,
	}.Build()
	File_mutter_proto = out.File
	file_mutter_proto_goTypes = nil
	file_mutter_proto_depIdxs = nil
}
