// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mutter.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sidisinsane/mutter/api/proto/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MutterServiceName is the fully-qualified name of the MutterService service.
	MutterServiceName = "mutter.v1.MutterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MutterServiceIndexProcedure is the fully-qualified name of the MutterService's Index RPC.
	MutterServiceIndexProcedure = "/mutter.v1.MutterService/Index"
	// MutterServiceRouteProcedure is the fully-qualified name of the MutterService's Route RPC.
	MutterServiceRouteProcedure = "/mutter.v1.MutterService/Route"
	// MutterServiceExecuteProcedure is the fully-qualified name of the MutterService's Execute RPC.
	MutterServiceExecuteProcedure = "/mutter.v1.MutterService/Execute"
	// MutterServiceExecuteStreamProcedure is the fully-qualified name of the MutterService's
	// ExecuteStream RPC.
	MutterServiceExecuteStreamProcedure = "/mutter.v1.MutterService/ExecuteStream"
)

// MutterServiceClient is a client for the mutter.v1.MutterService service.
type MutterServiceClient interface {
	// Index discovers and indexes hashfm-annotated scripts in the workspace.
	Index(context.Context, *connect.Request[v1.IndexRequest]) (*connect.Response[v1.IndexResponse], error)
	// Route matches a natural language query to the best matching script(s).
	Route(context.Context, *connect.Request[v1.RouteRequest]) (*connect.Response[v1.RouteResponse], error)
	// Execute runs a matched script with the provided arguments.
	Execute(context.Context, *connect.Request[v1.ExecuteRequest]) (*connect.Response[v1.ExecuteResponse], error)
	// ExecuteStream runs a script and streams the output in real-time.
	ExecuteStream(context.Context, *connect.Request[v1.ExecuteRequest]) (*connect.ServerStreamForClient[v1.ExecuteStreamResponse], error)
}

// NewMutterServiceClient constructs a client for the mutter.v1.MutterService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMutterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MutterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mutterServiceMethods := v1.File_mutter_proto.Services().ByName("MutterService").Methods()
	return &mutterServiceClient{
		index: connect.NewClient[v1.IndexRequest, v1.IndexResponse](
			httpClient,
			baseURL+MutterServiceIndexProcedure,
			connect.WithSchema(mutterServiceMethods.ByName("Index")),
			connect.WithClientOptions(opts...),
		),
		route: connect.NewClient[v1.RouteRequest, v1.RouteResponse](
			httpClient,
			baseURL+MutterServiceRouteProcedure,
			connect.WithSchema(mutterServiceMethods.ByName("Route")),
			connect.WithClientOptions(opts...),
		),
		execute: connect.NewClient[v1.ExecuteRequest, v1.ExecuteResponse](
			httpClient,
			baseURL+MutterServiceExecuteProcedure,
			connect.WithSchema(mutterServiceMethods.ByName("Execute")),
			connect.WithClientOptions(opts...),
		),
		executeStream: connect.NewClient[v1.ExecuteRequest, v1.ExecuteStreamResponse](
			httpClient,
			baseURL+MutterServiceExecuteStreamProcedure,
			connect.WithSchema(mutterServiceMethods.ByName("ExecuteStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mutterServiceClient implements MutterServiceClient.
type mutterServiceClient struct {
	index         *connect.Client[v1.IndexRequest, v1.IndexResponse]
	route         *connect.Client[v1.RouteRequest, v1.RouteResponse]
	execute       *connect.Client[v1.ExecuteRequest, v1.ExecuteResponse]
	executeStream *connect.Client[v1.ExecuteRequest, v1.ExecuteStreamResponse]
}

// Index calls mutter.v1.MutterService.Index.
func (c *mutterServiceClient) Index(ctx context.Context, req *connect.Request[v1.IndexRequest]) (*connect.Response[v1.IndexResponse], error) {
	return c.index.CallUnary(ctx, req)
}

// Route calls mutter.v1.MutterService.Route.
func (c *mutterServiceClient) Route(ctx context.Context, req *connect.Request[v1.RouteRequest]) (*connect.Response[v1.RouteResponse], error) {
	return c.route.CallUnary(ctx, req)
}

// Execute calls mutter.v1.MutterService.Execute.
func (c *mutterServiceClient) Execute(ctx context.Context, req *connect.Request[v1.ExecuteRequest]) (*connect.Response[v1.ExecuteResponse], error) {
	return c.execute.CallUnary(ctx, req)
}

// ExecuteStream calls mutter.v1.MutterService.ExecuteStream.
func (c *mutterServiceClient) ExecuteStream(ctx context.Context, req *connect.Request[v1.ExecuteRequest]) (*connect.ServerStreamForClient[v1.ExecuteStreamResponse], error) {
	return c.executeStream.CallServerStream(ctx, req)
}

// MutterServiceHandler is an implementation of the mutter.v1.MutterService service.
type MutterServiceHandler interface {
	// Index discovers and indexes hashfm-annotated scripts in the workspace.
	Index(context.Context, *connect.Request[v1.IndexRequest]) (*connect.Response[v1.IndexResponse], error)
	// Route matches a natural language query to the best matching script(s).
	Route(context.Context, *connect.Request[v1.RouteRequest]) (*connect.Response[v1.RouteResponse], error)
	// Execute runs a matched script with the provided arguments.
	Execute(context.Context, *connect.Request[v1.ExecuteRequest]) (*connect.Response[v1.ExecuteResponse], error)
	// ExecuteStream runs a script and streams the output in real-time.
	ExecuteStream(context.Context, *connect.Request[v1.ExecuteRequest], *connect.ServerStream[v1.ExecuteStreamResponse]) error
}

// NewMutterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMutterServiceHandler(svc MutterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mutterServiceMethods := v1.File_mutter_proto.Services().ByName("MutterService").Methods()
	mutterServiceIndexHandler := connect.NewUnaryHandler(
		MutterServiceIndexProcedure,
		svc.Index,
		connect.WithSchema(mutterServiceMethods.ByName("Index")),
		connect.WithHandlerOptions(opts...),
	)
	mutterServiceRouteHandler := connect.NewUnaryHandler(
		MutterServiceRouteProcedure,
		svc.Route,
		connect.WithSchema(mutterServiceMethods.ByName("Route")),
		connect.WithHandlerOptions(opts...),
	)
	mutterServiceExecuteHandler := connect.NewUnaryHandler(
		MutterServiceExecuteProcedure,
		svc.Execute,
		connect.WithSchema(mutterServiceMethods.ByName("Execute")),
		connect.WithHandlerOptions(opts...),
	)
	mutterServiceExecuteStreamHandler := connect.NewServerStreamHandler(
		MutterServiceExecuteStreamProcedure,
		svc.ExecuteStream,
		connect.WithSchema(mutterServiceMethods.ByName("ExecuteStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mutter.v1.MutterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MutterServiceIndexProcedure:
			mutterServiceIndexHandler.ServeHTTP(w, r)
		case MutterServiceRouteProcedure:
			mutterServiceRouteHandler.ServeHTTP(w, r)
		case MutterServiceExecuteProcedure:
			mutterServiceExecuteHandler.ServeHTTP(w, r)
		case MutterServiceExecuteStreamProcedure:
			mutterServiceExecuteStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMutterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMutterServiceHandler struct{}

func (UnimplementedMutterServiceHandler) Index(context.Context, *connect.Request[v1.IndexRequest]) (*connect.Response[v1.IndexResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mutter.v1.MutterService.Index is not implemented"))
}

func (UnimplementedMutterServiceHandler) Route(context.Context, *connect.Request[v1.RouteRequest]) (*connect.Response[v1.RouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mutter.v1.MutterService.Route is not implemented"))
}

func (UnimplementedMutterServiceHandler) Execute(context.Context, *connect.Request[v1.ExecuteRequest]) (*connect.Response[v1.ExecuteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mutter.v1.MutterService.Execute is not implemented"))
}

func (UnimplementedMutterServiceHandler) ExecuteStream(context.Context, *connect.Request[v1.ExecuteRequest], *connect.ServerStream[v1.ExecuteStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("mutter.v1.MutterService.ExecuteStream is not implemented"))
}
